Login: Login
Logout: Logout
NotAnAdmin: Sorry, you have to be an admin to do this

MainTitle: OI statistics

Olympiads: Olympiads
OlympiadName olympiad@Int: The #{show olympiad}. Olympiad in Informatics
StageName stage@Int: The #{show stage}. stage
CityTitle city@Text: The city of #{city}
ContestantTitle name@Text surname@Text: Contestant #{name} #{surname}
StageTitle olympiad@Int stage@Int: Results of the #{show stage}. stage of the #{show olympiad} Olympiad
ParseResultsTitle: Parse
SchoolTitle name@Text city@Text: School #{name} in #{city}

Representing: representing
Points pts@Int: #{show pts} points

StageResultsPosition: position
StageResultsAward: award
StageResultsName: name
StageResultsSurname: surname
StageResultsClass: class
StageResultsSchool: school
StageResultsCity: city
StageResultsSum: sum

ParseResultsAddedData: Added results
ParseResultsOlympiadIdent: Olympiad identifier
ParseResultsStageNumber: Stage number
ParseResultsURL: URL
ParseResultsParse: Parse
ParseResultsNegativeOlympiad: The olympiad identifier should be positive.
ParseResultsHTML: If you want to import custom HTML, enter it here:

LaureateI: gold
LaureateII: silver
LaureateIII: bronze
FinalistHonMen: hon. men.
Finalist: finalist
Advanced: advanced to the next round
Total: total

CitySchools: Schools
CityContestants: Contestants

StageToChart: Go to the charts
StageFromChart: Go back to the results

StageDelete: Delete stage
OlympiadDelete: Delete olympiad

NoStagesYet: Sorry, no stages yet...
NoOlympiadsYet: Sorry, no olympiads yet...

ChangeLanguage: Change

StageDeleted: Stage deleted
OlympiadDeleted: Olympiad deleted
SelectLanguage: Language

ContestantSearchName: Name
ContestantSearchSurname: Surname
ContestantSearchCity: City
ContestantSearchTitle: Search contestants
ContestantSearchFrom: from the city of:
ContestantSearchQuery: Additional query
ContestantSearchSearch: Search
ContestantSearchTooLong max@Int: Your query is too long. Limit: #{show max} characters

Contestants: Contestants

MergeSchoolsSelectSchools: Select schools to merge
MergeSchoolsName: Name of the school
MergeSchoolsSubmit: Merge
MergeSchoolsTitle: Merge schools
MergeSchools city@Text: Merge schools in #{city}
MergeSchoolsDone: Merged schools

MergeCitiesTitle: Merge and edit cities
MergeCitiesDone: Merged/edited cities
MergeCitiesSelectCities city@Text: Select cities to merge with #{city}
MergeCitiesName: Name
MergeCitiesLatitude: Latitude
MergeCitiesLongitude: Longitude
MergeCitiesSubmit: Merge
MergeCities city@Text: Merge and edit city #{city}

CityAdministration: Administration

ConfirmAreYouSure: Are you sure?
ConfirmDelete: Delete
ConfirmCancel: Cancel

Chart: Chart
List: List
Help: Help (additional queries)
HelpSearchOlympiad num@Int: List all contestants that participated in the #{show num}. olympiad
HelpSearchOlympiadStage olimp@Int stage@Int: List all contestants that are listed in the ranking of the #{show stage}. stage of the #{show olimp}. olympiad
HelpSearchNotStage stage@Int: List all contestants that are not listed in the ranking of the #{show stage}. stage of any olympiad
HelpSearchStageResult stage@Int points@Int: List all contestants that are listed in the rankng of the #{show stage}. stage and receivd at least #{show points} points there
HelpSearchOlympiadStageResult olymp@Int stage@Int points@Int: List all contestants that are listed in the rankng of the #{show stage}. stage of the #{show olymp}. olympiad and received less than #{show points} points there
HelpSearchCompositeQuery: The queries may be nested like that
SearchNoResults: No results
