Login: Zaloguj się
Logout: Wyloguj się
NotAnAdmin: Niestety musisz być administratorem aby to uczynić

MainTitle: Statystyki OI

Olympiads: Olimpiady
OlympiadName olympiad@Int: #{show olympiad}. Olimpiada Informatyczna
StageName stage@Int: #{show stage}. etap
CityTitle city@Text: Miasto #{city}
ContestantTitle name@Text surname@Text: Zawodnik #{name} #{surname}
StageTitle olympiad@Int stage@Int: Wyniki #{show stage}. etapu #{show olympiad} olimpiady
ParseResultsTitle: Sparsuj nowe wyniki
SchoolTitle name@Text city@Text: Szkoła #{name} w mieście #{city}

Representing: reprezentując
Points pts@Int: #{show pts} punktów

StageResultsPosition: lp
StageResultsAward: nagroda
StageResultsName: imię
StageResultsSurname: nazwisko
StageResultsClass: klasa
StageResultsSchool: szkoła
StageResultsCity: miasto
StageResultsSum: suma

ParseResultsAddedData: Dodano wyniki
ParseResultsOlympiadIdent: Numer olimpiady
ParseResultsStageNumber: Numer etapu
ParseResultsURL: URL
ParseResultsParse: Sparsuj
ParseResultsNegativeOlympiad: Numer olimpiady powinien być dodatni.
ParseResultsHTML: Jeśli chcesz sparsować niestandardowy HTML, wpisz go tu:

LaureateI: złoto
LaureateII: srebro
LaureateIII: brąz
FinalistHonMen: wyróżnienie
Finalist: finalista
Advanced: zakwalifikowany
Total: razem

CitySchools: Szkoły
CityContestants: Zawodnicy

StageToChart: Idź do wykresów
StageFromChart: Wróć do wyników

StageDelete: Usuń etap
OlympiadDelete: Usuń olimpiadę

NoStagesYet: Niestety nie ma tu jeszcze żadnych etapów...
NoOlympiadsYet: Niestety nie ma tu jeszcze żadnych olimpiad...

ChangeLanguage: Zmień

StageDeleted: Skasowano etap
OlympiadDeleted: Skasowano olimpiadę
SelectLanguage: Język

ContestantSearchName: Imię
ContestantSearchSurname: Nazwisko
ContestantSearchCity: Miasto
ContestantSearchTitle: Wyszukaj zawodników
ContestantSearchFrom: z miasta:
ContestantSearchQuery: Dodatkowe zapytanie
ContestantSearchSearch: Wyszukaj

Contestants: Zawodnicy

MergeSchoolsSelectSchools: Wybierz szkoły do połączenia
MergeSchoolsName: Nazwa szkoły
MergeSchoolsSubmit: Połącz
MergeSchoolsTitle: Połącz szkoły
MergeSchools city@Text: Połącz szkoły w mieście: #{city}
MergeSchoolsDone: Połączono szkoły

MergeCitiesTitle: Połącz i edytuj miasta
MergeCitiesDone: Połączono/zmodyfikowano miasta
MergeCitiesSelectCities city@Text: Wybierz miasta do połączenia z: #{city}
MergeCitiesName: Nazwa
MergeCitiesLatitude: Szerokość geograficzna
MergeCitiesLongitude: Długość geograficzna
MergeCitiesSubmit: Połącz
MergeCities city@Text: Połącz i edytuj miasto: #{city}

CityAdministration: Administracja

ConfirmAreYouSure: Czy jesteś pewien?
ConfirmDelete: Usuń
ConfirmCancel: Anuluj

Chart: Mapka
List: Lista
Help: Pomoc (dodatkowe zapytania)
HelpSearchOlympiad num@Int: Wyświetla wszystkich zawodników, którzy uczestniczyli w #{show num} olimpiadzie
HelpSearchOlympiadStage olimp@Int stage@Int: Wyświetla wszystkich zawodników, którzy są w rankingu #{show stage} etapu #{show olimp} olimpiady
HelpSearchNotStage stage@Int: Wyświetla wszystkich zawodników, których nie ma w rankingu #{show stage} etapu żadnej olimpiady
HelpSearchStageResult stage@Int points@Int: Wyświetla wszystkich zawodników, którzy w rankingu #{show stage} etapu jakiejkolwiek olimpiady mają przynajmniej #{show points} punktów
HelpSearchOlympiadStageResult olymp@Int stage@Int points@Int: Wyświetla wszystkich zawodników, którzy w rankingu #{show stage} etapu #{show olymp} olimpiady mają mniej niż #{show points} punktów
HelpSearchCompositeQuery: Zapytania można zagnieżdżać
SearchNoResults: Brak wyników
